
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Yu WenRui  ## put your name
title: 'currently a graduate student at NanJing University'  ## your title
location: Nanjing, JiangSu, CHINA


## Social Profiles
Wechat: y15951980614  ## your facebook account url
QQ: 1114681435  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
